#!/usr/bin/env sh
#
# Author: Daniele Sluijters, Umer Farooq
# Source: https://github.com/farooqu/mdadm-ntfy
# License: GPLv3
# Version: 0.1.0

required_system_utils="cut logger curl dirname"
for util in $required_system_utils; do
    command -v "$util" >/dev/null 2>&1 || {
        echo >&2 "Could not find $util. Please use your system package manager to install it."; exit 1;
    }
done

NTFY_SERVER=
TOPIC=
TOKEN_FILE="$(dirname "$0")/mdadm-ntfy.token"
if [ -f "$TOKEN_FILE" ]; then
    NTFY_TOKEN=$(< "$TOKEN_FILE")
fi

send_message() {
    local priority=$1
    local summary=$2
    local body=$3
    local tag=""
    local ntfy_server="${NTFY_SERVER:-https://ntfy.sh}"
    local topic="${TOPIC:-mdadm}"
    local curl_args=()

    if [ "$priority" = 'urgent' ]; then
        tag='rotating_light'
    fi

    curl_args=(
        -H "Title: mdadm notification"
        -H "Priority: $priority"
    )

    if [ -n "$tag" ]; then
        curl_args+=(-H "Tags: $tag")
    fi

    if [ -n "$body" ]; then
        curl_args+=(-d "$summary

$body")
    else
        curl_args+=(-d "$summary")
    fi

    if [ -n "$NTFY_TOKEN" ]; then
        curl_args+=(-H "Authorization: Bearer $NTFY_TOKEN")
    fi

    curl "${curl_args[@]}" "$ntfy_server/$topic"
}

EVENT=$1
ARRAY=$2
DEVICE=$3

case "$EVENT" in
    'DeviceDisappeared')
        send_message 'urgent' "Array $ARRAY has disappeared"
        ;;
    'RebuildStarted')
        send_message 'normal' "Rebuild was started for $ARRAY"
        ;;
    'RebuildFinished')
        send_message 'normal' "Rebuild for $ARRAY has completed" 'Please note that it **may have succeeded** or **have failed**. You need to inspect the status of the array by hand'
        ;;
    'Rebuild'[0-9][0-9])
        percent=$(echo "$EVENT" | cut -c8,9)
        send_message 'normal' "Rebuild of $ARRAY at ${percent}%"
        ;;
    'Fail')
        send_message 'urgent' "$ARRAY has marked device $DEVICE as faulty"
        ;;
    'FailSpare')
        send_message 'urgent' "Rebuild failed for $DEVICE" "Failed to replace a faulty device in $ARRAY"
        ;;
    'SpareActive')
        send_message 'default' "Rebuild succesfull for $DEVICE" "Replaced a faulty device in $ARRAY"
        ;;
    'NewArray')
        send_message 'normal' "New array $ARRAY has been detected"
        ;;
    'DegradedArray')
        send_message 'urgent' "Array $ARRAY is degraded"
        ;;
    'MoveSpare')
        send_message 'normal' "Spare from $DEVICE was moved to $ARRAY"
        ;;
    'SpareMissing')
        send_message 'urgent' "Spare(s) missing from $ARRAY" 'There are less spares available than required by its configuration'
        ;;
    'TestMessage')
        send_message 'low' "Found array $ARRAY at startup (test)"
        ;;
    *)
        logger -t 'mdadm-notify' "Unhandled message of type: $EVENT with arguments $ARRAY $DEVICE"
esac

exit 0
